name: 'Build and Install MoltenVK and DXVK'
description: 'Action that builds MoltenVK and DXVK and bundles them in a common installation'
inputs:
  crossover-source:
    description: 'Path to the crossover source (i.e. the directory that contains the "moltenvk" and "dxvk" directories'
    required: true
    default: ${{ github.workspace }}/sources
  install-prefix:
    description: 'Installation target directory for MoltenVK and DXVK'
    required: true
    # default: ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}

runs:
  using: "composite"
  steps:

    - name: Applying patches to DXVK
      shell: bash
      run: |
        pushd ${{ inputs.crossover-source }}/dxvk
        patch -p1 < ${{ github.workspace }}/0001-build-macOS-Fix-up-for-macOS.patch
        patch -p1 < ${{ github.workspace }}/0002-fix-d3d11-header-for-MinGW-9-1883.patch
        patch -p1 < ${{ github.workspace }}/0003-fixes-for-mingw-gcc-12.patch
        popd

    - name: Patch MoltenVK for Monterey support (no python 2.7 any more)
      shell: bash
      run: |
        pushd ${{ inputs.crossover-source }}/moltenvk
        patch < ${{ github.workspace }}/moltenvk_python3.patch
        popd

    ############ Build and Install MoltenVK ##############
    - name: Build MoltenVK
      shell: bash
      run: |
        pushd ${{ inputs.crossover-source }}/moltenvk
        ./fetchDependencies --macos
        make macos
        popd

    - name: Install MoltenVK
      shell: bash
      run: |
        set -x

        pushd ${{ inputs.crossover-source }}/moltenvk/Package/Latest/MoltenVK
        mkdir -p ${{ inputs.install-prefix }}/usr/local/lib/
        cp ./dylib/macOS/*.dylib ${{ inputs.install-prefix }}/usr/local/lib/
        cp -r ./include ${{ inputs.install-prefix }}/usr/local/
        popd

        # also copy the spirv-headers as VKD3D seems to need them for building
        pushd ${{ inputs.crossover-source }}/moltenvk/External/glslang/External/spirv-tools/external/spirv-headers/include/
        cp -r ./spirv ${{ inputs.install-prefix }}/usr/local/include/

        popd

    ############ Build and Install DXVK ##############
    - name: Get latest HomeBrew formulas/bottles
      shell: bash
      run: |
        brew update

    - name: Install Dependencies for DXVK
      shell: bash
      run: |
        brew install  glslang   \
                      mingw-w64 \
                      meson

    - name: Build DXVK
      shell: bash
      run: |
        set -x
        pushd ${{ inputs.crossover-source }}/dxvk

        ./package-release.sh master ${{ inputs.crossover-source }}/dxvk/install --no-package
        popd

    - name: Install DXVK
      shell: bash
      run: |
        set -x
        pushd ${{ inputs.crossover-source }}/dxvk/install/dxvk-master

        echo Installing DXVK dlls...
        mkdir -p ${{ inputs.install-prefix }}/usr/local/lib64/wine
        cp -r x64 ${{ inputs.install-prefix }}/usr/local/lib64/wine/dxvk

        echo Installing DXVK setup script...
        mkdir -p ${{ inputs.install-prefix }}/usr/local/bin
        cp setup_dxvk.sh ${{ inputs.install-prefix }}/usr/local/bin/

        popd
